// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ-jZJt0c7e3fD3D0BYvGBdpA1Gj5Spao',
    appId: '1:350180192875:web:5e0b98e888aa14a25cf72e',
    messagingSenderId: '350180192875',
    projectId: 'be-mandaluyong-4sight',
    authDomain: 'be-mandaluyong-4sight.firebaseapp.com',
    storageBucket: 'be-mandaluyong-4sight.firebasestorage.app',
    measurementId: 'G-VTRW5BNQ14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA9MLwufKO0lLWy7m_LVKSH9gU9Znp7RE',
    appId: '1:350180192875:android:5c32249b0c0381b25cf72e',
    messagingSenderId: '350180192875',
    projectId: 'be-mandaluyong-4sight',
    storageBucket: 'be-mandaluyong-4sight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIyMC4pBuqdI30JwvLv3-zcbQU0-MajUM',
    appId: '1:350180192875:ios:d5da4628674ebea65cf72e',
    messagingSenderId: '350180192875',
    projectId: 'be-mandaluyong-4sight',
    storageBucket: 'be-mandaluyong-4sight.firebasestorage.app',
    iosBundleId: 'com.example.beMandaluyong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIyMC4pBuqdI30JwvLv3-zcbQU0-MajUM',
    appId: '1:350180192875:ios:d5da4628674ebea65cf72e',
    messagingSenderId: '350180192875',
    projectId: 'be-mandaluyong-4sight',
    storageBucket: 'be-mandaluyong-4sight.firebasestorage.app',
    iosBundleId: 'com.example.beMandaluyong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ-jZJt0c7e3fD3D0BYvGBdpA1Gj5Spao',
    appId: '1:350180192875:web:c5eafc9df7174d675cf72e',
    messagingSenderId: '350180192875',
    projectId: 'be-mandaluyong-4sight',
    authDomain: 'be-mandaluyong-4sight.firebaseapp.com',
    storageBucket: 'be-mandaluyong-4sight.firebasestorage.app',
    measurementId: 'G-4TCB9TK1XF',
  );
}
